const styles = (theme: Object) => ({
  summaryBody: {
    height: 'calc(100% - 70px)',
    display: 'flex',
    flexDirection: 'column',
    alignItems: 'center',
    justifyContent: 'flex-start',
  },
  summaryTitle: {
    fontSize: '15px',
    fontWeight: 600,
    fontStyle: 'normal',
    letterSpacing: '-0.1px',
    margin: '12px 0',
    alignSelf: 'flex-start',
    paddingLeft: '15px',
    color: theme.palette.neutrals.mainText,
  },
  card: {
    marginTop: '20px',
    padding: '10px',
    width: '50%',
    minWidth: '870px',
    display: 'flex',
    flexFlow: 'column',
    overflowY: 'auto',
    boxShadow: 'none',
    paddingBottom: '25px',
  },
  signee: {
    display: 'flex',
    width: '96.6%',
    margin: 'auto',
    borderBottom: `1px solid ${theme.palette.backgrounds.main}`,
    padding: '10px 0',
  },
  avatarIcon: {
    marginRight: '14px',
  },
  signeeDetails: {
    overflow: 'hidden',
    width: '95%',
    margin: 'auto 0',
  },
  signeeName: {
    fontSize: '15px',
    width: '15%',
    color: theme.palette.neutrals.mainText,
    float: 'left',
  },
  signeeEmail: {
    fontSize: '15px',
    float: 'left',
    color: theme.palette.neutrals.mainText,
  },
  document: {
    display: 'flex',
    width: '96.6%',
    margin: 'auto',
    borderBottom: `1px solid ${theme.palette.backgrounds.main}`,
    padding: '10px 0',
  },
  docIcon: {
    float: 'left',
    marginRight: '14px',
  },
  docTitle: {
    fontSize: '15px',
    margin: 'auto 0',
    float: 'left',
    width: '95%',
    color: theme.palette.neutrals.mainText,
  },
  formContainer: {
    margin: 'auto 0px',
    paddingLeft: '15px',
    width: '100%',
  },
  formTitle: {
    opacity: 0.5,
    fontSize: '10px',
    padding: '5px 0',
    paddingBottom: 0,
  },
  titleInput: {
    border: 'none',
    width: '96.6%',
    borderBottom: '1px solid rgba( 0, 0, 0, 0.5)',
    font: theme.palette.neutrals.secondaryGrey,
  },
  bodyInput: {
    width: '96.6%',
    margin: '0',
  },
  sendButton: {
    position: 'absolute',
    bottom: 0,
    padding: '0',
    width: '100%',
    height: '80px',
    backgroundColor: '#78BF6F',
    color: theme.palette.primary.contrastText,
    fontSize: '24px',
  },
  characterCount: {
    opacity: 0.5,
    width: '96.6%',
    textAlign: 'right',
    fontSize: '10px',
    paddingTop: '5px',
    paddingBottom: '5px',
  },
  view: {
    position: 'relative',
    overflow: 'scroll',
    height: '100%',
  },
  tooltip: {
    overflow: 'hidden',
    backgroundColor: theme.palette.primary.main,
    minWidth: 'fit-content',
    overflowWrap: 'break-word',
    wordBreak: 'break-all',
    display: 'flex',
    alignSelf: 'center',
    alignItems: 'center',
    justifyContent: 'center',
  },
  hide: {
    display: 'none',
  },
});

export default styles;
