// flow-typed signature: e2f304df4513f0ae9d19ff5874458d66
// flow-typed version: <<STUB>>/apollo-link-error_v1.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'apollo-link-error'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'apollo-link-error' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'apollo-link-error/lib/bundle.umd' {
  declare module.exports: any;
}

declare module 'apollo-link-error/lib/index' {
  declare module.exports: any;
}

declare module 'apollo-link-error/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'apollo-link-error/lib/bundle.umd.js' {
  declare module.exports: $Exports<'apollo-link-error/lib/bundle.umd'>;
}
declare module 'apollo-link-error/lib/index.js' {
  declare module.exports: $Exports<'apollo-link-error/lib/index'>;
}
declare module 'apollo-link-error/rollup.config.js' {
  declare module.exports: $Exports<'apollo-link-error/rollup.config'>;
}
