// flow-typed signature: f29304ac5e7b84a73f528e9f8552a9f6
// flow-typed version: <<STUB>>/lodash.omit_v4.x.x/flow_v0.89.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'lodash.omit'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'lodash.omit' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'lodash.omit/index' {
  declare module.exports: $Exports<'lodash.omit'>;
}
declare module 'lodash.omit/index.js' {
  declare module.exports: $Exports<'lodash.omit'>;
}
