// flow-typed signature: 4491ba2bbca60a0b2dd3c9bc1cc4d4ba
// flow-typed version: <<STUB>>/react-router-breadcrumbs-hoc_v2.x.x/flow_v0.70.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-router-breadcrumbs-hoc'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-router-breadcrumbs-hoc' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-router-breadcrumbs-hoc/coverage/lcov-report/block-navigation' {
  declare module.exports: any;
}

declare module 'react-router-breadcrumbs-hoc/coverage/lcov-report/prettify' {
  declare module.exports: any;
}

declare module 'react-router-breadcrumbs-hoc/coverage/lcov-report/sorter' {
  declare module.exports: any;
}

declare module 'react-router-breadcrumbs-hoc/dist/es/index' {
  declare module.exports: any;
}

declare module 'react-router-breadcrumbs-hoc/dist/umd/index' {
  declare module.exports: any;
}

declare module 'react-router-breadcrumbs-hoc/jest.config' {
  declare module.exports: any;
}

declare module 'react-router-breadcrumbs-hoc/jest.setup' {
  declare module.exports: any;
}

declare module 'react-router-breadcrumbs-hoc/rollup.config' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-router-breadcrumbs-hoc/coverage/lcov-report/block-navigation.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/coverage/lcov-report/block-navigation'>;
}
declare module 'react-router-breadcrumbs-hoc/coverage/lcov-report/prettify.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/coverage/lcov-report/prettify'>;
}
declare module 'react-router-breadcrumbs-hoc/coverage/lcov-report/sorter.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/coverage/lcov-report/sorter'>;
}
declare module 'react-router-breadcrumbs-hoc/dist/es/index.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/dist/es/index'>;
}
declare module 'react-router-breadcrumbs-hoc/dist/umd/index.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/dist/umd/index'>;
}
declare module 'react-router-breadcrumbs-hoc/jest.config.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/jest.config'>;
}
declare module 'react-router-breadcrumbs-hoc/jest.setup.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/jest.setup'>;
}
declare module 'react-router-breadcrumbs-hoc/rollup.config.js' {
  declare module.exports: $Exports<'react-router-breadcrumbs-hoc/rollup.config'>;
}
