// flow-typed signature: 590be322b39453dad7cd33143fbf3042
// flow-typed version: <<STUB>>/react-grecaptcha_v1.2.5/flow_v0.79.1

/**
 * This is an autogenerated libdef stub for:
 *    circle ci bplease build
 *   'react-grecaptcha'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-grecaptcha' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-grecaptcha/lib/index' {
  declare module.exports: any;
}

declare module 'react-grecaptcha/lib/Recaptcha' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-grecaptcha/lib/index.js' {
  declare module.exports: $Exports<'react-grecaptcha/lib/index'>;
}
declare module 'react-grecaptcha/lib/Recaptcha.js' {
  declare module.exports: $Exports<'react-grecaptcha/lib/Recaptcha'>;
}
