// flow-typed signature: 5cfbf8198177deac97ebc241fed79776
// flow-typed version: <<STUB>>/signature_pad_v~2.3.2/flow_v0.74.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'signature_pad'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'signature_pad' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'signature_pad/dist/signature_pad' {
  declare module.exports: any;
}

declare module 'signature_pad/dist/signature_pad.min' {
  declare module.exports: any;
}

declare module 'signature_pad/example/js/app' {
  declare module.exports: any;
}

declare module 'signature_pad/example/js/signature_pad' {
  declare module.exports: any;
}

declare module 'signature_pad/src/bezier' {
  declare module.exports: any;
}

declare module 'signature_pad/src/point' {
  declare module.exports: any;
}

declare module 'signature_pad/src/signature_pad' {
  declare module.exports: any;
}

declare module 'signature_pad/src/throttle' {
  declare module.exports: any;
}

// Filename aliases
declare module 'signature_pad/dist/signature_pad.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad'>;
}
declare module 'signature_pad/dist/signature_pad.min.js' {
  declare module.exports: $Exports<'signature_pad/dist/signature_pad.min'>;
}
declare module 'signature_pad/example/js/app.js' {
  declare module.exports: $Exports<'signature_pad/example/js/app'>;
}
declare module 'signature_pad/example/js/signature_pad.js' {
  declare module.exports: $Exports<'signature_pad/example/js/signature_pad'>;
}
declare module 'signature_pad/src/bezier.js' {
  declare module.exports: $Exports<'signature_pad/src/bezier'>;
}
declare module 'signature_pad/src/point.js' {
  declare module.exports: $Exports<'signature_pad/src/point'>;
}
declare module 'signature_pad/src/signature_pad.js' {
  declare module.exports: $Exports<'signature_pad/src/signature_pad'>;
}
declare module 'signature_pad/src/throttle.js' {
  declare module.exports: $Exports<'signature_pad/src/throttle'>;
}
