// flow-typed signature: edc9af2e69fe30066f251a1836eccbc3
// flow-typed version: <<STUB>>/text-to-svg_v3.x.x/flow_v0.94.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'text-to-svg'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'text-to-svg' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'text-to-svg/build/src/index' {
  declare module.exports: any;
}

declare module 'text-to-svg/build/test/browser' {
  declare module.exports: any;
}

declare module 'text-to-svg/build/test/html-reporter' {
  declare module.exports: any;
}

declare module 'text-to-svg/build/test/index' {
  declare module.exports: any;
}

declare module 'text-to-svg/src/index' {
  declare module.exports: any;
}

declare module 'text-to-svg/test/browser' {
  declare module.exports: any;
}

declare module 'text-to-svg/test/html-reporter' {
  declare module.exports: any;
}

declare module 'text-to-svg/test/index' {
  declare module.exports: any;
}

// Filename aliases
declare module 'text-to-svg/build/src/index.js' {
  declare module.exports: $Exports<'text-to-svg/build/src/index'>;
}
declare module 'text-to-svg/build/test/browser.js' {
  declare module.exports: $Exports<'text-to-svg/build/test/browser'>;
}
declare module 'text-to-svg/build/test/html-reporter.js' {
  declare module.exports: $Exports<'text-to-svg/build/test/html-reporter'>;
}
declare module 'text-to-svg/build/test/index.js' {
  declare module.exports: $Exports<'text-to-svg/build/test/index'>;
}
declare module 'text-to-svg/index' {
  declare module.exports: $Exports<'text-to-svg'>;
}
declare module 'text-to-svg/index.js' {
  declare module.exports: $Exports<'text-to-svg'>;
}
declare module 'text-to-svg/src/index.js' {
  declare module.exports: $Exports<'text-to-svg/src/index'>;
}
declare module 'text-to-svg/test/browser.js' {
  declare module.exports: $Exports<'text-to-svg/test/browser'>;
}
declare module 'text-to-svg/test/html-reporter.js' {
  declare module.exports: $Exports<'text-to-svg/test/html-reporter'>;
}
declare module 'text-to-svg/test/index.js' {
  declare module.exports: $Exports<'text-to-svg/test/index'>;
}
