// flow-typed signature: 283620d13f6e124115eec3c8376feb62
// flow-typed version: <<STUB>>/react-jss/lib/JssProvider_v9.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-jss/lib/JssProvider'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-jss/lib/JssProvider' {
  declare module.exports: any;
}
