// flow-typed signature: 3e99e9360ac939ad0e398fe23a58f99e
// flow-typed version: <<STUB>>/moment/locale/en-ca_v2.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment/locale/en-ca'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment/locale/en-ca' {
  declare module.exports: any;
}
