// flow-typed signature: e6b9b48fe42a40cc3dc0f9d7848c05a0
// flow-typed version: <<STUB>>/moment/locale/es_v2.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment/locale/es'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment/locale/es' {
  declare module.exports: any;
}
