// flow-typed signature: e18edf05336a08bc5b45b7db48bd3644
// flow-typed version: <<STUB>>/moment/locale/fr-ca_v2.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'moment/locale/fr-ca'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'moment/locale/fr-ca' {
  declare module.exports: any;
}
