// flow-typed signature: 5e128609b7045e1f087273d7a9897ba9
// flow-typed version: <<STUB>>/react-intl/locale-data/en_v2.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl/locale-data/en'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl/locale-data/en' {
  declare module.exports: any;
}
