// flow-typed signature: 3ee39cd1720c1ac61ba2e7aa7e57ed6c
// flow-typed version: <<STUB>>/react-intl/locale-data/es_v2.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl/locale-data/es'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl/locale-data/es' {
  declare module.exports: any;
}
