// flow-typed signature: bcf10e5206c7585621bdfe5bcb125cc0
// flow-typed version: <<STUB>>/react-intl/locale-data/fr_v2.x.x/flow_v0.87.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-intl/locale-data/fr'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-intl/locale-data/fr' {
  declare module.exports: any;
}
